### ISSUE TITLE
peer review - Header

### ISSUE THREAD

**Issue by undrbug** [GabrielaBaldissone/mercado-liebre-PG#2]
1 - **Footer**: 
                  - En el footer, en lo iconos, entiendo que el requerimiento dice margin-bottom de 10px. (es una pavada completamente irrelevante jajajaj)
                  - En la version desktop (a partir de 1024px) en las cards se superponen el precio y el descuento (por lo menos en mi pantalla)
                  -
![image](https://github.com/GabrielaBaldissone/mercado-liebre-PG/assets/68193647/3eb7c079-0640-4324-b133-98f451d347dd)

                  - Se repite la superposicion de precio y descuento en la version tablet (769px) y tambien en 481px

![image](https://github.com/GabrielaBaldissone/mercado-liebre-PG/assets/68193647/f97e21dc-6802-4235-9bcc-211558de4b91)

* Me encanta tu trabajo! esta muy bueno. Se nota que le dedicaste tiempo y te fijaste en muchos detalles. Te voy a robar algunas ideas jajajajaja
* Es dificil sugerir mejoras. Yo le agregaria border radius a las cards. Pero es una cuestion de gustos personal.

**Comment by GabrielaBaldissone** [comment]
Solucionado. Mil gracias.
